# ineuron numpy assignment


### Problem statement 1
    Write a function so that the columns of the output matrix are powers of the input
    vector.
    The order of the powers is determined by the increasing boolean argument. Specifically, when
    increasing is False, the i-th output column is the input vector raised element-wise to the power
    of N - i - 1.

    HINT: Such a matrix with a geometric progression in each row is named for Alexandre-
    Theophile Vandermonde.

In [1]:
import numpy as np

In [20]:
# Build vandermonde functionality
def vandermonde_functionality(input_array, output_columns=0, power_order=False):
    if(output_columns==0):
        output_columns=len(input_array)
    print(np.vander(input_array,output_columns,power_order))
    

In [19]:
# testing vandermonde function for different inputs
input_array = np.array([1,2,3,4])
vandermonde_functionality(input_array,3)

[[ 1  1  1]
 [ 4  2  1]
 [ 9  3  1]
 [16  4  1]]


In [21]:
vandermonde_functionality(input_array,2,True)

[[1 1]
 [1 2]
 [1 3]
 [1 4]]


## Problem Statment 2
    Given a sequence of n values x1, x2, ..., xn and a window size k>0, the k-th moving average of
    the given sequence is defined as follows:
    The moving average sequence has n-k+1 elements as shown below.
    The moving averages with k=4 of a ten-value sequence (n=10) is shown below
    i 1 2 3 4 5 6 7 8 9 10
    ===== == == == == == == == == == ==
    Input 10 20 30 40 50 60 70 80 90 100
    y1 25 = (10+20+30+40)/4
    y2 35 = (20+30+40+50)/4
    y3 45 = (30+40+50+60)/4
    y4 55 = (40+50+60+70)/4
    y5 65 = (50+60+70+80)/4
    y6 75 = (60+70+80+90)/4
    y7 85 = (70+80+90+100)/4
    Thus, the moving average sequence has n-k+1=10-4+1=7 values.
    
    Question: Write a function to find moving average in an array over a window:
Test it over [3, 5, 7, 2, 8, 10, 11, 65, 72, 81, 99, 100, 150] and window of 3.

In [80]:
def moving_avg(input_data, window_size):
    n=len(input_data)
    for i in range(n-window_size+1):
        print('y',i,'', int(np.sum([input_array[i + x ] for x in range(window_size) ],dtype=np.int32)/window_size))

In [81]:
# testing moving_avg for sifferent inputs
input_x1 = [10,20,30,40,50,60,70,80,90,100]

moving_avg(input_array,4)

y 0  25
y 1  35
y 2  45
y 3  55
y 4  65
y 5  75
y 6  85


In [82]:
input_x2= [3, 5, 7, 2, 8, 10, 11, 65, 72, 81, 99, 100, 150]
moving_avg(input_array,3)

y 0  5
y 1  4
y 2  5
y 3  6
y 4  9
y 5  28
y 6  49
y 7  72
y 8  84
y 9  93
y 10  116
